# Site settings
title: Snow D. J.
email: snowdj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Phd student. Topics on my site include
  my teaching interests, R, LaTeX, and professional development.
baseurl: "/econcourse/" # the subpath of your site, e.g. /blog/
url: "http://snowdj.github.io" # the base hostname & protocol for your site
twitter_username: snowdj1984
github_username:  snowdj

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
job.title: "Phd"
excerpt_separator: "<!--more-->"

# SEO stuff
#google_author: "https://plus.google.com/u/0/110288225974212014913"
#google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
#bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

gems:
  - jekyll-sitemap
